apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accent.fullname" . }}
  labels:
    {{- include "accent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.accent.replicas }}
  selector:
    matchLabels:
      {{- include "accent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "accent.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.accent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.accent.securityContext | nindent 12 }}
          image: "{{ .Values.accent.image.repository }}:{{ .Values.accent.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.accent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.accent.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.accent.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "accent.fullname" . }}
            {{- if .Values.postgresql.enabled }}
            - secretRef:
                name: {{ include "postgres.fullname" . }}-secret
            {{- end }}
---
{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    app: {{ include "postgres.fullname" . }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      {{- include "postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgres.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "postgres.fullname" . }}-pvc
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgres.fullname" . }}-secret
                  key: postgres-password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: {{ .Values.postgres.service.port }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
{{- end }}
