{{- if .Values.accent.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "accent.fullname" . }}
  labels:
    {{- include "accent.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "accent.fullname" . }}
  minReplicas: {{ .Values.accent.hpa.minReplicas }}
  maxReplicas: {{ .Values.accent.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.accent.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.accent.hpa.targetMemoryUtilizationPercentage }}
{{- end }}
